### PR TITLE
Better log formatting

### PR DESCRIPTION
**Pull request by benrudolph**
@esoergel 
minor formatting change, but will help a lot in getting performance of requests so we can start measuring on prod which requests take a long time

### CODE REVIEW

**Comment by esoergel** [comment]
Looks good.  Not entirely sure how to wire it up end-to-end, but wanted to flag that you can specify various formatters in the logging config dict: https://github.com/dimagi/commcare-hq/blob/master/settings.py#L764-L773  The idea is you'd register a specific logger for xformserver or whatever, then tell it to use this formatter.  This works too though.

**Comment by benrudolph** [comment]
Yea, would be nice to have it there. right now though this is very divorced from anything django. i saw that django 1.7 works with jython. then we might be able to share settings

**Comment by dannyroberts** [comment]
Maybe I'm missing context for why we want to change, but FWIW I think letting touchforms have its own localsettings seems totally reasonable if the concept is to have it be its own independent service, which I think is for the most part already the case.

**Comment by esoergel** [comment]
:+1: I was more thinking about keeping formatting config in *a* localsettings (rather than defining in-line) - definitely in favor of touchforms being an entirely separate service.

**Comment by benrudolph** [comment]
ah got it. yea, would be nice for every log file to have the same format somehow

**Comment by benrudolph** [comment]
:+1:

**Pull request merged**
