### PR TITLE
Update libs to 2.19

### PR DESCRIPTION
**Pull request by wpride**
fixes for log()

### CODE REVIEW

**Comment by czue** [comment]
@wpride does this need any QA ?

**Comment by czue** [comment]
@wpride is putting this on staging for QA. @wpride please confirm if that's not correct or update when QA is done

**Comment by wpride** [comment]
roger that's a big 10-4 ghost rider

**Comment by wpride** [comment]
@czue this is now in QA in this branch:

https://github.com/dimagi/touchforms/tree/mobile-libs-219

**Pull request closed without merging**
