### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by benrudolph**
This is ancient code, not sure if it's even being used still. At least we have one working server test now. hold off on merge until https://github.com/dimagi/touchforms/pull/90 is merged so I can add it to travis. @millerdev @czue

### CODE REVIEW

**Comment by czue** [comment]
lol

**Comment by czue** [comment]
classic ridiculous whitespace

**Comment by czue** [comment]
@benrudolph looked closer and we can just ditch everything related to bootstrapping things with static forms.

**Comment by czue** [comment]
let me know if you'd like to do that or whether you'd rather just get this merged.

**Comment by benrudolph** [comment]
let's ditch. i'm all for getting rid of any code that's not being used in this repo

**Comment by benrudolph** [comment]
Ok pretty aggressively removed it from the codebase. do we still need the ability to load a form from file? it seems like that was used for /webforms, but may not be used elsewhere

**Comment by czue** [comment]
I think just webforms. probably worth keeping the functionality around for now (if nothing else for those fun touchforms demos)

**Comment by czue** [comment]
looks good to me, will merge if you're good / after the no merge label is removed

**Comment by benrudolph** [comment]
sounds good. yea, i messed up travis anyways. gonna fix in another PR. travis.yml has to be in the root directory which is kind of annoying for this project

**Pull request merged**
