### PR TITLE
Use classes instead of ids

### PR DESCRIPTION
**Pull request by benrudolph**
@czue

### CODE REVIEW

**Comment by czue** [comment]
lol. looks good, do we need to do QA or you're pretty confident?

**Comment by czue** [comment]
(feel free to self merge if you're not worried about testing)

**Comment by dannyroberts** [comment]
:clap:

**Comment by benrudolph** [comment]
couldn't hurt to do a bit of QA though i feel decently comfortable with this. added some tests too for rendering a form and ensuring some basic bindings work

**Comment by benrudolph** [comment]
or we can do the dimagi way:
02fe36bc-e43c-11e4-8c70-72d4cd72024c

**Comment by czue** [comment]
was going to merge but looks like build failed:
```
Test the formplayer Entrycontrols Should render a select question
  TypeError: 'undefined' is not an object (evaluating 'window.JST[JST_BASE_DIR + 'fullform-ui/form.html']') in http://localhost:8889/__src__/script/fullform-ui.js (line 140)
  TypeError: 'undefined' is not an object (evaluating 'window.JST[JST_BASE_DIR + 'fullform-ui/form.html']')
    at Form (http://localhost:8889/__src__/script/fullform-ui.js:140)
    at init_render (http://localhost:8889/__src__/script/fullform-ui.js:582)
    at http://localhost:8889/__spec__/formplayer_spec.js:90
Test the formplayer Entrycontrols Should render a repeater question
  TypeError: 'undefined' is not an object (evaluating 'window.JST[JST_BASE_DIR + 'fullform-ui/form.html']') in http://localhost:8889/__src__/script/fullform-ui.js (line 140)
  TypeError: 'undefined' is not an object (evaluating 'window.JST[JST_BASE_DIR + 'fullform-ui/form.html']')
    at Form (http://localhost:8889/__src__/script/fullform-ui.js:140)
    at init_render (http://localhost:8889/__src__/script/fullform-ui.js:582)
    at http://localhost:8889/__spec__/formplayer_spec.js:102
```

**Comment by benrudolph** [comment]
thanks, i think i'll notify christy actually. it'll be good to have a test plan in place even if this is a small change. and after today i'd rather err on the side of caution

**Comment by snopoke** [comment]
+1 while I'm still on interrupt :)

**Comment by benrudolph** [comment]
let's merge this guy

**Comment by dannyroberts** [comment]
If you say so!

**Pull request merged**
