### PR TITLE
Speed up form submissions for SQL backend

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride did some looking into why form submissions were slow. I'm pretty sure this is the cause. i just straight up removed it because i couldn't figure out what it was doing and it worked fine when i removed it. let me know if you think that is wrong

cc: @sravfeyn

### CODE REVIEW

**Comment by wpride** [comment]
@benrudolph this is the code that actually causes the new form to be processed in the user's CaseDB. IE if they close a case in the form, this will close that case in the SQLiteDB. Without this you'd need to sync every time you made a transaction.

**Comment by czue** [comment]
any way we could move this asynchronously?

**Comment by benrudolph** [comment]
hmm, that's unfortunate. yeah this would be a perfect case for something like celery. we don't have that infrastructure in the old touchforms, but will mentioned possibly using threading which might work

**Comment by benrudolph** [comment]
@wpride for now i just updated it with a comment explaining what that portion is used for. agree that is should be async though. until we figure out why that's slow i'm imagining we won't be able to resolve slow submits

**Pull request merged**
