### PR TITLE
Push max date ten years into future

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?169219

There's similar code in submodules/touchforms-src/touchforms/formplayer/static/formplayer/script/deprecate/entrycontrols_type.js ... @benrudolph any idea if that directory is in use?

@TylerSheffels

### CODE REVIEW

**Comment by benrudolph** [comment]
It's currently not in use. I tried to move everything that I thought wasn't being used into the deprecate folder until we are sure we can remove it

**Comment by benrudolph** [comment]
:+1: will merge after tests

**Comment by orangejenny** [comment]
@benrudolph Cool. Totally uninformed opinion, but is deleting files altogether any more likely to break things than renaming them?

**Comment by benrudolph** [comment]
well, i updated the links that reference them so everything should still work. what i should do is log everytime they're loaded so I actually know if they're being used

**Comment by orangejenny** [comment]
@benrudolph ah, that makes sense

**Pull request merged**
