### PR TITLE
add missing bracket

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?167781

introduced here: https://github.com/dimagi/touchforms/commit/a6ddf069ec6fc3a10e9ac0a0f786d914bb1cebbd

@sravfeyn

### CODE REVIEW

**Comment by proteusvacuum** [comment]
wow, nice find

**Comment by kaapstorm** [comment]
Well spotted. I totally missed that.

**Comment by czue** [comment]
oops. maybe we'll do it a little less live next time.

**Comment by benrudolph** [comment]
:see_no_evil:

**Pull request merged**
