### PR TITLE
Jython 2.7

### PR DESCRIPTION
**Pull request by benrudolph**
Going to be upgrading things to work with jython 2.7 on this PR. With 2.7 we have the opportunity to use a wider variety of webframeworks
@esoergel

### CODE REVIEW

**Comment by esoergel** [comment]
https://travis-ci.org/dimagi/touchforms/jobs/61840955
build failure looks real:
```
./run_tests.sh: line 1: jython: command not found
The command "./run_tests.sh" exited with 127.
```

**Comment by benrudolph** [comment]
yea, still unclear to me why travis can't find the executable for 2.7 and it can for 2.5.3. going to try and sort out

**Comment by esoergel** [comment]
I didn't realize that Jython 2.7 just came out like [a week ago](fwierzbicki.blogspot.com/2015/05/jython-270-final-released.html).  Are you sure it's stable enough?

**Comment by benrudolph** [comment]
Not too sure, it looks like they've been working on it for a while. The beta came out in 2013: http://www.jython.org/. this is kind of experimental. not going to push too hard on it

**Comment by esoergel** [comment]
I mean if it's a proper release (as you said, it's not beta), I imagine
it'd be fine.

On Mon, May 11, 2015 at 11:21 AM, Ben <notifications@github.com> wrote:

> Not too sure, it looks like they've been working on it for a while. The
> beta came out in 2013: http://www.jython.org/. this is kind of
> experimental. not going to push too hard on it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/touchforms/pull/108#issuecomment-100941807>.
>



--

**Pull request closed without merging**
