### PR TITLE
Create .lintrc

### PR DESCRIPTION
**Pull request by benrudolph**

### CODE REVIEW

**Comment by benrudolph** [comment]
@millerdev 
ignore tests errors. working on it

**Comment by millerdev** [comment]
@benrudolph do you want this merged even though there are test errors?

**Comment by benrudolph** [comment]
i guess i thought this might make lint-review work. let me read the README more closely on lint-review. i'll get back to you

**Comment by benrudolph** [comment]
@esoergel i think i need this merged in order for dimagimon to activate

**Pull request merged**
