### PR TITLE
New libs

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride new jars to put on staging

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by ctsims** [comment]
Hey,

As a heads up we have _not_ done QA on these libraries and don't know
whether they are stable yet, should we really be pushing them to touchforms?

**Comment by wpride** [comment]
Not merging yet, just need the repeat fix to test bens refactor on staging
@ctsims

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Pull request merged**
