### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by benrudolph**

### CODE REVIEW

**Comment by benrudolph** [comment]
@millerdev

**Comment by millerdev** [comment]
Travis failed:
```
Could not open requirements file: [Errno 2] No such file or directory: 'test_requirements'
```

**Comment by benrudolph** [comment]
yea i believe that's cause the current travis.yml is missing the -r

**Comment by benrudolph** [comment]
nvm

**Comment by benrudolph** [comment]
god damn that should do it. the proper place to run django tests is from the HQ testrunner.

**Comment by czue** [comment]
:white_check_mark: !

**Pull request merged**
