### PR TITLE
use edit form property in FormDef init + 227 libs

### PR DESCRIPTION
**Pull request by wpride**
See http://manage.dimagi.com/default.asp?212637

Cross https://github.com/dimagi/javarosa/pull/285
Cross https://github.com/dimagi/commcare-hq/pull/11138

check the id_editing session value and pass into the FormDef initialization

### CODE REVIEW

**Comment by wpride** [comment]
@dannyroberts FYI fix for 212637

@benrudolph The rollout strategy for this will either be long or a bit uncomfortable. The JR functionality won't get into the release until 2.28 meaning this shouldn't be merged until then if we wanted to wait. Other possibility would be to QA this along with the 2.27 jars (IE I make a 2.27 + this build) and merge after that passes. 

cc @czue this means we can delete all that static_handler hackiness ya?

**Comment by benrudolph** [comment]
rough, any idea how urgent this is? if it's a bug that they need fixed then we'll have to go the 2.27 + this build QA route

**Comment by benrudolph** [comment]
test failure looks real:
```
======================================================================
ERROR: test_load_form_with_context (__main__.XFormPlayerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "backend/test_xformplayer.py", line 74, in test_load_form_with_context
    xformplayer.load_form(
  File "/home/travis/build/dimagi/touchforms/touchforms/backend/xformplayer.py", line 161, in load_form
    form.initialize(instance is None, is_editing, CCInstances(session_data,
  File "/home/travis/build/dimagi/touchforms/touchforms/backend/xformplayer.py", line 161, in load_form
    form.initialize(instance is None, is_editing, CCInstances(session_data,
NoSuchMethodError: java.lang.NoSuchMethodError: org.javarosa.core.model.instance.TreeElement.BuildRef(Lorg/javarosa/core/model/instance/AbstractTreeElement;)Lorg/javarosa/core/model/instance/TreeReference;
```

**Comment by wpride** [comment]
I don't think urgent but nice to have. Cut a new branch with just this fix +2.27 that we can run QA on - don't think that's a huge issue since we already QA separately.

Test fail involved missing the commcare 2.27 lib, should be gtg now

@czue to confirm/deny fix urgency

**Comment by czue** [comment]
> this means we can delete all that static_handler hackiness ya?

sounds right

> @czue to confirm/deny fix urgency

confirming that I don't think this is urgent so fine to wait. might be worth confirming with robin and meryn

**Comment by wpride** [comment]
see http://manage.dimagi.com/default.asp?223255#1123180

**Comment by wpride** [comment]
QA passed http://manage.dimagi.com/default.asp?223255

**Comment by wpride** [comment]
@benrudolph @czue This is GTM

**Comment by dannyroberts** [comment]
Talked with @wspride and agreed this is itself an improvement that didn't need to wait for the "don't shift to UTC" bug that's been the main focus of me and Will's conversations.

**Comment by czue** [comment]
sweet. :candy:

**Comment by czue** [comment]
@wpride @dannyroberts don't we need to merge https://github.com/dimagi/commcare-hq/pull/11138 too? it still has a "don't merge" label on it

**Pull request merged**
